### ISSUE TITLE
Fix _ConcurrentTestGateRunner: missing IWorkflowGateRunner methods

### ISSUE THREAD

**Issue by MikeyVK** [MikeyVK/phase-gate-mcp#355]
# Fix _ConcurrentTestGateRunner: missing IWorkflowGateRunner methods

## Problem
_ConcurrentTestGateRunner in tests/mcp_server/integration/test_phase_state_engine_concurrent.py is missing the four IWorkflowGateRunner interface methods introduced by #293 C2-GREEN: enforce_phase_exit(), inspect_phase_exit(), enforce_cycle_exit(), inspect_cycle_exit(). The class still has the old enforce()/inspect() stubs that were replaced. This causes AttributeError when force_transition() or force_cycle_transition() call inspect_phase_exit() via phase_state_engine.py:247.

## Expected Behavior

_ConcurrentTestGateRunner implements the current IWorkflowGateRunner boundary: enforce_phase_exit, inspect_phase_exit, enforce_cycle_exit, inspect_cycle_exit. Old enforce()/inspect() stubs removed. Both failing tests pass.
## Actual Behavior

AttributeError: '_ConcurrentTestGateRunner' object has no attribute 'inspect_phase_exit' raised by two concurrent integration tests:
- TestPrimaryMixedConcurrentWritesC4::test_force_transition_and_force_cycle_transition_concurrent
- TestSecondaryHomogeneousConcurrentWritesC4::test_two_concurrent_force_transitions_both_records_present
## Steps to Reproduce

Run: pytest tests/mcp_server/integration/test_phase_state_engine_concurrent.py -v
## Context

Root cause: issue #293 C2-GREEN (commit d1da4053) replaced enforce()/inspect() with enforce_phase_exit(), inspect_phase_exit(), enforce_cycle_exit(), inspect_cycle_exit() in IWorkflowGateRunner. Production engine and StubGateRunner in test_support.py were updated. _ConcurrentTestGateRunner was created later by #292 C4-GREEN (commit d8f2a6b4) and never received the new interface. Pre-existing failure, not introduced by #353.

**Comment by MikeyVK** [comment]
Opgelost — `_ConcurrentTestGateRunner` geüpdatet met de vier ontbrekende `IWorkflowGateRunner` methoden. Beide falende concurrent integration tests slagen. Gemerged via de pull op epic/320 (commit 099377da).
